// <auto-generated />
using System;
using CriptoApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CriptoApi.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220623190105_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("CriptoApi.Models.Coins", b =>
                {
                    b.Property<int>("ModenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("ModenaId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            ModenaId = 1,
                            Descripcion = "Bitcoin",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/bitcoin.png",
                            Valor = 20300.099999999999
                        },
                        new
                        {
                            ModenaId = 2,
                            Descripcion = "Ethereum",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/ethereum.png",
                            Valor = 1094.9000000000001
                        },
                        new
                        {
                            ModenaId = 3,
                            Descripcion = "Tether",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/tether.png",
                            Valor = 0.99890000000000001
                        },
                        new
                        {
                            ModenaId = 4,
                            Descripcion = "BNB",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/bnb.png",
                            Valor = 223.99000000000001
                        },
                        new
                        {
                            ModenaId = 5,
                            Descripcion = "Binance USD",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/binance-usd.png",
                            Valor = 1.0008999999999999
                        },
                        new
                        {
                            ModenaId = 6,
                            Descripcion = "Cordano",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/cardano.png",
                            Valor = 0.46839999999999998
                        },
                        new
                        {
                            ModenaId = 7,
                            Descripcion = "XRP",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/xrp.png",
                            Valor = 0.32617000000000002
                        },
                        new
                        {
                            ModenaId = 8,
                            Descripcion = "Solana",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/solana.png",
                            Valor = 37.460000000000001
                        },
                        new
                        {
                            ModenaId = 9,
                            Descripcion = "Dogecoin",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/dogecoin.png",
                            Valor = 0.062323999999999997
                        },
                        new
                        {
                            ModenaId = 10,
                            Descripcion = "Polkadot",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/polkadot-new.png",
                            Valor = 7.5289999999999999
                        },
                        new
                        {
                            ModenaId = 11,
                            Descripcion = "Dai",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/multi-collateral-dai.png",
                            Valor = 0.99970000000000003
                        },
                        new
                        {
                            ModenaId = 12,
                            Descripcion = "TRON",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/tron.png",
                            Valor = 0.062389
                        },
                        new
                        {
                            ModenaId = 13,
                            Descripcion = "UNUS SED LEO",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/unus-sed-leo.png",
                            Valor = 5.9316000000000004
                        },
                        new
                        {
                            ModenaId = 14,
                            Descripcion = "Shiba Inu",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/shiba-inu.png",
                            Valor = 1.0000000000000001E-05
                        },
                        new
                        {
                            ModenaId = 15,
                            Descripcion = "Wrapped Bitcoin",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/wrapped-bitcoin.png",
                            Valor = 20263.25
                        },
                        new
                        {
                            ModenaId = 16,
                            Descripcion = "Avalanche",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/avalanche.png",
                            Valor = 17.350000000000001
                        },
                        new
                        {
                            ModenaId = 17,
                            Descripcion = "Polygon",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/polygon.png",
                            Valor = 0.49399999999999999
                        },
                        new
                        {
                            ModenaId = 18,
                            Descripcion = "Uniswap",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/uniswap.png",
                            Valor = 5.2400000000000002
                        },
                        new
                        {
                            ModenaId = 19,
                            Descripcion = "Litecoin",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/litecoin.png",
                            Valor = 54.700000000000003
                        },
                        new
                        {
                            ModenaId = 20,
                            Descripcion = "FTX Token",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/ftx-token.png",
                            Valor = 25.378799999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
